name: "Release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Release"
        uses: "ncipollo/release-action@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cache-and-install:
    needs: [release]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          settings-path: .npmrc

      - name: Install dependencies
        run: pnpm install

  npm_publish:
    name: publish to npm
    needs: [release , cache-and-install ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}